[versions]
agp = "8.13.1"
googleGmsGoogleServices = "4.4.3"
kotlin = "2.0.21"
androidx_core = "1.12.0"
androidx_lifecycle_runtime = "2.6.2"
androidx_activity_compose = "1.9.2"
compose_bom = "2024.09.00"
compose_ui = "1.6.0"
compose_material3 = "1.2.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
firebaseDatabase = "20.2.0"
navigationRuntimeAndroid = "2.9.5"

[libraries]
androidx_core_ktx = { module = "androidx.core:core-ktx", version.ref = "androidx_core" }
androidx_lifecycle_runtime_ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx_lifecycle_runtime" }
androidx_activity_compose = { module = "androidx.activity:activity-compose", version.ref = "androidx_activity_compose" }
androidx_compose_bom = { module = "androidx.compose:compose-bom", version.ref = "compose_bom" }
androidx_compose_ui = { module = "androidx.compose.ui:ui", version.ref = "compose_ui" }
androidx_compose_ui_graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose_ui" }
androidx_compose_ui_tooling_preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose_ui" }
androidx_compose_material3 = { module = "androidx.compose.material3:material3", version.ref = "compose_material3" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx_junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx_espresso_core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# Firebase
firebase_database = { group = "com.google.firebase", name = "firebase-database-ktx", version.ref = "firebaseDatabase" }

# Navigation
androidx_navigation_runtime_android = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigationRuntimeAndroid" }

[plugins]
android_application = { id = "com.android.application", version.ref = "agp" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google_gms_google_services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
parcelize = { id = "kotlin-parcelize", version.ref = "kotlin" }
